import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f6fa" },
  scroll: { flex: 1 },
  headerButton: {
    paddingHorizontal: 5,
  },
  menuScrollContent: {
    paddingBottom: 12,
  },

  // Hero section
  heroSection: { backgroundColor: "#a8d8f2", overflow: "hidden" },
  heroContent: {
    width: "100%",
    alignSelf: "center",
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 12,
  },
  productionBlock: {
    flex: 1,
    minWidth: 190,
  },
  prodLabel: { fontSize: 14, fontWeight: "600", color: "#2a4060" },
  prodValue: {
    fontSize: 36,
    fontWeight: "700",
    color: "#1a3050",
    lineHeight: 43,
  },
  prodUnit: { fontSize: 19, fontWeight: "400" },
  weatherRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
    flexShrink: 0,
  },
  tempText: { fontSize: 20, fontWeight: "600", color: "#2a3c50" },

  // Hero visual
  heroVisual: {
    position: "relative",
  },
  sceneWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: -4,
    alignItems: "center",
  },
  toHomeBubblePosition: {
    position: "absolute",
    zIndex: 2,
  },
  solarPowerBubblePosition: {
    position: "absolute",
    top: 0,
    left: "50%",
    zIndex: 3,
  },
  fromGridBubblePosition: {
    position: "absolute",
    zIndex: 2,
  },
  bubble: {
    backgroundColor: "rgba(255,255,255,0.88)",
    justifyContent: "center",
    alignItems: "center",
  },
  bubbleValueRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  bubbleValue: { fontWeight: "600", color: "#5a7a9a" },
  bubbleUnit: {
    fontSize: 11,
    color: "#7a9ab0",
    marginBottom: 3,
    marginLeft: 2,
  },
  bubbleLabel: {
    fontSize: 10,
    color: "#6a8aa8",
    textAlign: "center",
    lineHeight: 14,
    marginTop: 2,
  },

  // Energy Produced
  contentFrame: {
    width: "100%",
    alignSelf: "center",
  },
  energyProducedCard: {
    backgroundColor: "white",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  epRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "#1a2a3a" },
  updatedNow: { fontSize: 12, color: "#aaa" },
  epStats: { flexDirection: "row", alignItems: "center", flexWrap: "wrap" },
  epItem: { flex: 1, minWidth: 96, alignItems: "center" },
  epLabel: { fontSize: 12, color: "#888", marginBottom: 2 },
  epValue: { fontSize: 20, fontWeight: "700", color: "#1a2a3a" },
  epUnit: { fontSize: 12, fontWeight: "400", color: "#666" },
  epDivider: { width: 1, height: 36, backgroundColor: "#e8e8e8" },

  // Tabs
  stickyPeriodHeader: {
    backgroundColor: "white",
    zIndex: 10,
    elevation: 4,
    alignItems: "center",
  },
  tabBar: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: "#f0f0f5",
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  tabItem: { flex: 1, minWidth: 0, alignItems: "center" },
  tabActiveChip: {
    backgroundColor: "#4285f4",
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tabActiveText: {
    color: "white",
    fontWeight: "600",
    fontSize: 13,
    textAlign: "center",
  },
  tabText: { color: "#666", fontSize: 13, textAlign: "center" },

  dateNav: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    minHeight: 60,
    paddingHorizontal: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#eeeeee",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#d9d9d9",
  },
  dateNavSide: {
    width: 72,
    minHeight: 48,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  dateNavRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 14,
  },
  dateNavIconButton: {
    minWidth: 24,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  dateNavIconButtonDisabled: {
    opacity: 0.45,
  },
  dateNavCenter: {
    flex: 1,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  dateNavCenterText: {
    flexShrink: 1,
    fontSize: 15,
    lineHeight: 20,
    color: "#6EA0F6",
    fontWeight: "300",
    textAlign: "center",
  },
  calendarOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 24,
  },
  calendarDialog: {
    width: "100%",
    maxWidth: 420,
    minHeight: 456,
    borderRadius: 18,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  calendarTitle: {
    color: "#333",
    fontSize: 18,
    fontWeight: "600",
    paddingHorizontal: 28,
    paddingTop: 24,
  },
  calendarSelectedRow: {
    minHeight: 92,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 28,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#dddddd",
  },
  calendarSelectedText: {
    flex: 1,
    color: "#333",
    fontSize: 34,
    fontWeight: "400",
    marginRight: 16,
  },
  calendarMonthRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 28,
  },
  calendarMonthText: {
    color: "#777",
    fontSize: 20,
    fontWeight: "400",
  },
  calendarMonthControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 28,
  },
  calendarMonthButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarMonthButtonDisabled: {
    opacity: 0.35,
  },
  calendarWeekRow: {
    flexDirection: "row",
    paddingHorizontal: 28,
    marginTop: 8,
  },
  calendarWeekText: {
    flex: 1,
    color: "#333",
    fontSize: 20,
    textAlign: "center",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 28,
    paddingTop: 18,
  },
  calendarDayCell: {
    width: `${100 / 7}%`,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDayInRange: {
    backgroundColor: "#eaf1ff",
  },
  calendarDayCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDaySelected: {
    backgroundColor: "#5d8ff6",
  },
  calendarDayText: {
    color: "#777",
    fontSize: 22,
    fontWeight: "400",
  },
  calendarDayMuted: {
    color: "#c7c7c7",
  },
  calendarDaySelectedText: {
    color: "#fff",
  },
  calendarOptionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    minHeight: 280,
    paddingHorizontal: 28,
    paddingTop: 24,
  },
  calendarOptionCell: {
    width: "25%",
    height: 76,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarOptionCircle: {
    minWidth: 76,
    height: 76,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  calendarOptionSelected: {
    backgroundColor: "#5d8ff6",
  },
  calendarOptionDisabled: {
    opacity: 0.35,
  },
  calendarOptionText: {
    color: "#333",
    fontSize: 22,
    fontWeight: "400",
  },
  calendarOptionSelectedText: {
    color: "#fff",
  },
  calendarOptionDisabledText: {
    color: "#9a9a9a",
  },
  calendarActionRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingHorizontal: 24,
    gap: 28,
  },
  calendarActionBtn: {
    minWidth: 64,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarActionText: {
    color: "#6EA0F6",
    fontSize: 18,
  },

  // White sections
  whiteSection: {
    backgroundColor: "white",
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },

  // Energy Balance
  balanceSubLabel: {
    fontSize: 14,
    color: "#555",
    marginTop: 12,
    marginBottom: 4,
  },
  balanceBigValue: {
    fontSize: 36,
    fontWeight: "700",
    color: "#1a2a3a",
    lineHeight: 44,
  },
  balanceUnit: { fontSize: 18, fontWeight: "400", color: "#666" },
  barTrack: {
    flexDirection: "row",
    height: 10,
    borderRadius: 5,
    overflow: "hidden",
    marginVertical: 10,
    backgroundColor: "#eee",
  },
  barFill: { height: 10 },
  toHomeBarFill: { backgroundColor: "#4caf50" },
  toGridBarFill: { backgroundColor: "#42b0e8" },
  fromSolarBarFill: { backgroundColor: "#42b0e8" },
  fromGridBarFill: { backgroundColor: "#f5a623" },
  donutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginVertical: 8,
  },
  legendCol: { flex: 1, gap: 10 },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  dot: { width: 10, height: 10, borderRadius: 5 },
  balanceToHomeDot: { backgroundColor: "#4caf50" },
  balanceToGridDot: { backgroundColor: "#42b0e8" },
  balanceFromSolarDot: { backgroundColor: "#42b0e8" },
  balanceFromGridDot: { backgroundColor: "#f5a623" },
  year2025Dot: { backgroundColor: "#42b0e8" },
  year2026Dot: { backgroundColor: "#4e5ab5" },
  legendLabel: { fontSize: 13, color: "#555", flex: 1, minWidth: 86 },
  legendValue: {
    fontSize: 13,
    color: "#333",
    fontWeight: "500",
    flexShrink: 1,
  },
  separator: { height: 1, backgroundColor: "#eee", marginVertical: 14 },
  selfConsumptionRow: { marginTop: 12 },
  selfText: { fontSize: 13, color: "#555" },
  selfBold: { fontWeight: "700", color: "#1a2a3a" },
  productionDot: { backgroundColor: "#04b850" },
  productionRing: { borderColor: "#04b850" },
  consumptionDot: { backgroundColor: "#ff9800" },
  consumptionRing: { borderColor: "#ff9800" },
  toGridDot: { backgroundColor: "#16b8cc" },
  toGridRing: { borderColor: "#16b8cc" },
  fromSolarDot: { backgroundColor: "#2e86de" },
  fromSolarRing: { borderColor: "#2e86de" },
  selfDot: { backgroundColor: "#2e86de" },
  selfRing: { borderColor: "#2e86de" },

  // Chart
  chartHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  chartTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: "#1a2a3a",
  },
  expandButton: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
  },
  expandIcon: { fontSize: 36, color: "#888" },
  infoIcon: { fontSize: 18, color: "#999" },

  tooltipBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#222",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignSelf: "center",
    marginBottom: 4,
  },
  tooltipText: { color: "white", fontSize: 13, fontWeight: "500" },
  splitChartBlock: {
    marginTop: 18,
  },

  chartLegendRow: {
    flexDirection: "row",
    gap: 20,
    marginTop: 10,
    flexWrap: "wrap",
  },
  chartLegendRowCompact: {
    gap: 10,
    flexWrap: "nowrap",
  },
  chartLegendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  chartLegendItemCompact: { gap: 4, flexShrink: 1 },
  chartLegendText: { fontSize: 13, color: "#444" },
  chartLegendTextMuted: { fontSize: 13, color: "#888" },
  chartLegendTextCompact: { fontSize: 11, flexShrink: 1 },
  chartLegendTextSmall: { fontSize: 12, color: "#888", lineHeight: 17 },
  checkCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  checkCircleCompact: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  checkDot: { width: 10, height: 10, borderRadius: 5 },
  checkDotCompact: { width: 8, height: 8, borderRadius: 4 },

  // Toggle Merged/Split
  toggleRow: {
    flexDirection: "row",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4285f4",
    overflow: "hidden",
    marginBottom: 16,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "white",
  },
  toggleBtnActive: { backgroundColor: "#eef3ff" },
  toggleText: { fontSize: 14, color: "#555" },
  toggleTextActive: { color: "#4285f4", fontWeight: "600" },

  // Sub-tabs
  subTabRow: {
    flexDirection: "row",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4285f4",
    overflow: "hidden",
    marginBottom: 8,
  },
  subTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    backgroundColor: "white",
  },
  subTabActive: { backgroundColor: "#eef3ff" },
  subTabText: { fontSize: 13, color: "#555" },
  subTabTextActive: { color: "#4285f4", fontWeight: "600" },

  // Environmental
  envRow: { flexDirection: "row", marginTop: 12 },
  envItem: { flex: 1, alignItems: "center", gap: 4 },
  envValue: { fontSize: 30, fontWeight: "700", color: "#1a2a3a" },
  envLabel: {
    fontSize: 12,
    color: "#888",
    textAlign: "center",
    lineHeight: 18,
  },

  // Expanded chart
  expandedSafe: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  expandedHeader: {
    minHeight: 112,
    paddingTop: 42,
    paddingHorizontal: 12,
    backgroundColor: "#000633",
    flexDirection: "row",
    alignItems: "center",
  },
  expandedBackButton: {
    width: 48,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  expandedHeaderTitle: {
    flex: 1,
    color: "#fff",
    fontSize: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  expandedHeaderSpacer: {
    width: 48,
  },
  expandedCompareTabs: {
    width: "100%",
    alignSelf: "center",
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f4",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d2d2d6",
    borderRadius: 8,
    padding: 2,
  },
  expandedCompareTab: {
    flex: 1,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
  },
  expandedCompareTabActive: {
    backgroundColor: "#eef8ff",
    borderWidth: 1,
    borderColor: "#6ea0f6",
  },
  expandedCompareTabText: {
    color: "#333333",
    fontSize: 16,
    lineHeight: 22,
  },
  expandedCompareTabTextActive: {
    color: "#6ea0f6",
    fontWeight: "600",
  },
  expandedCompareChartWrap: {
    marginTop: 92,
  },
  expandedContent: {
    flex: 1,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 14,
  },
  expandedTitle: {
    fontSize: 20,
    lineHeight: 25,
    color: "#333333",
    marginBottom: 22,
  },
  expandedTooltipCard: {
    width: "78%",
    minWidth: 260,
    maxWidth: 430,
    borderWidth: 1,
    borderColor: "#b9c3da",
    borderRadius: 6,
    backgroundColor: "#eef8ff",
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginLeft: 28,
    marginBottom: 4,
  },
  expandedTooltipDate: {
    color: "#81869d",
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 14,
  },
  expandedTooltipMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  expandedTooltipLabel: {
    flex: 1,
    color: "#81869d",
    fontSize: 18,
    lineHeight: 25,
  },
  expandedTooltipValue: {
    color: "#81869d",
    fontSize: 18,
    lineHeight: 25,
    textAlign: "right",
  },
  expandedLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 18,
    marginTop: 8,
    paddingHorizontal: 8,
  },
  expandedLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    maxWidth: "100%",
  },
  expandedLegendDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  expandedLegendText: {
    color: "#777b92",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600",
    flexShrink: 1,
  },
});
