export * from "./auth/AuthApi";
export {
  getList,
  getFieldActive,
  getPropertyClass,
  getDetails,
  getClassReference,
  getListHistory,
  getListAttachFile,
  getPreviewAttachFile,
  getBuildTree,
  getDetailsHistory,
  getPreviewAttachProperty,
  getPreviewBC,
  callApi,
  insert,
  update,
  deleteItems,
  checkReferenceUsage,
  uploadAttachProperty,
  getPermission,
} from "./data/CallApi";
