import { StyleSheet } from "react-native";
import { C } from "../../utils/helpers/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.surface,
  },
  headerIconButton: {
    width: 38,
    height: 38,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  form: {
    padding: 16,
    paddingBottom: 28,
    gap: 12,
  },
  formScroll: {
    flex: 1,
  },
  parameterField: {
    gap: 7,
  },
  parameterLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: C.text,
  },
  required: {
    color: C.red,
  },
  parameterInput: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.borderStrong,
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    fontSize: 14,
    color: C.text,
  },
  input: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.borderStrong,
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    fontSize: 14,
    color: C.text,
  },
  textArea: {
    minHeight: 92,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.borderStrong,
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: C.text,
  },
  boolRow: {
    minHeight: 36,
    paddingHorizontal: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  boolLabel: {
    flex: 1,
    paddingRight: 12,
  },
  tooltipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  tooltipLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: C.textSecondary,
  },
  tooltipText: {
    flex: 1,
    fontSize: 12,
    color: C.textMuted,
  },
  uploadButton: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.borderStrong,
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  previewImage: {
    width: "100%",
    height: 160,
    borderRadius: 8,
    backgroundColor: C.surfaceAlt,
  },
  removeImageButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButton: {
    backgroundColor: C.red,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center" as const,
  },
  submitButtonLoading: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold" as const,
  },
  reportLoadingText: {
    color: C.textMuted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    paddingHorizontal: 12,
    textAlign: "center",
  },
  toolbar: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 12,
    backgroundColor: C.surface,
  },
  toolbarButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    backgroundColor: C.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  reportContainer: {
    flex: 1,
    backgroundColor: C.bg,
  },
  reportContainerLandscape: {
    backgroundColor: "#000",
  },
  reportWebView: {
    flex: 1,
  },
  landscapeControls: {
    position: "absolute",
    top: 18,
    right: 18,
    flexDirection: "row",
    gap: 10,
    padding: 4,
  },
  landscapeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.52)",
  },
  shareSheet: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 18,
    paddingBottom: 22,
  },
  shareSheetTitle: {
    textAlign: "center",
    fontSize: 17,
    fontWeight: "800",
    color: C.text,
    marginBottom: 12,
  },
  shareOptionList: {
    gap: 8,
  },
  shareOptionItem: {
    minHeight: 54,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  shareOptionIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.redSurface,
    marginRight: 10,
  },
  shareOptionText: {
    flex: 1,
    color: C.text,
    fontSize: 14.5,
    fontWeight: "700",
  },
  renderOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.loadingOverlay,
    gap: 10,
  },
  renderOverlayText: {
    fontSize: 13,
    color: C.textSecondary,
    fontWeight: "600",
    lineHeight: 19,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  fullscreenContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  fsHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 10,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: "#000",
  },
  fsHeaderLandscape: {
    paddingTop: 48,
  },
  fsHeaderBtn: {
    padding: 6,
  },
  fsTitle: {
    flex: 1,
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
    marginHorizontal: 4,
  },
  fullscreenReportArea: {
    flex: 1,
    backgroundColor: C.bg,
  },
});
