import { StyleSheet } from "react-native";
import { C } from "../../utils/helpers/colors";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  offlineState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  topHalf: {
    backgroundColor: "#000",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  topHalfFullscreen: { flex: 1, justifyContent: "center" },
  gridViewport: { backgroundColor: "#000", overflow: "hidden" },
  grid: { flexDirection: "row", flexWrap: "wrap" },
  cell: {
    backgroundColor: "#111",
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: "#2a2a2a",
  },
  activeBorder: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 2,
    borderColor: "#e53935",
  },
  cellTop: { flexDirection: "row", padding: 4 },
  cellBottom: {
    marginTop: "auto",
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  cellLabel: { color: "#fff", fontSize: 8 },
  cellPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#1a1a1a",
    alignItems: "center",
    justifyContent: "center",
  },
  cellPlaceholderText: { color: C.textMuted, fontSize: 8, textAlign: "center" },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(229,57,53,0.9)",
    borderRadius: 3,
    paddingHorizontal: 5,
    paddingVertical: 2,
    gap: 4,
  },
  liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#fff" },
  liveText: { color: "#fff", fontSize: 8, fontWeight: "700" },
  paginationRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: 28,
    backgroundColor: C.surface,
    gap: 4,
    paddingHorizontal: 12,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: C.borderStrong,
  },
  dotActive: {
    width: 22,
    height: 7,
    backgroundColor: "#e53935",
    borderRadius: 4,
  },
  bottomHalf: { flex: 4, backgroundColor: C.bg },
  toolbar: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingVertical: 18,
  },
  toolBtn: { alignItems: "center", justifyContent: "center" },
  sdBadge: {
    borderWidth: 1.5,
    borderColor: C.textSecondary,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  sdText: { fontSize: 12, fontWeight: "700", color: C.textSecondary },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: C.border,
    marginHorizontal: 20,
  },
  actionContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  playbackBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surfaceAlt,
    borderRadius: 30,
    paddingHorizontal: 22,
    paddingVertical: 12,
    marginRight: 20,
  },
  playbackBtnDisabled: { opacity: 0.5 },
  playbackText: {
    marginLeft: 6,
    fontSize: 15,
    fontWeight: "600",
    color: C.text,
  },
  playbackTextDisabled: { color: C.placeholder },
  iconGroup: { flex: 1, flexDirection: "row", justifyContent: "space-between" },
  iconBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  chevronWrapper: { alignItems: "center", paddingBottom: 8 },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  modalOverlayLandscape: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  sheetContainer: {
    backgroundColor: C.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  sheetContainerLandscape: {
    width: "100%",
    maxWidth: 520,
    borderRadius: 24,
  },
  handleWrapper: { alignItems: "center", paddingTop: 10, paddingBottom: 6 },
  handle: {
    width: 45,
    height: 5,
    backgroundColor: C.borderStrong,
    borderRadius: 3,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 8,
    color: C.text,
  },
  sheetTitleChild: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 12,
    color: C.textMuted,
  },
  listItem: { paddingVertical: 16, paddingHorizontal: 20 },
  listItemText: { fontSize: 16, color: C.text, textAlign: "center" },
  itemBorder: { borderTopWidth: 0.5, borderColor: C.border },
  activeItem: { backgroundColor: C.surfaceAlt },
  activeText: { color: C.red, fontWeight: "600" },
  closeBtn: {
    marginTop: 10,
    marginHorizontal: 16,
    backgroundColor: C.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  closeText: { fontSize: 16, fontWeight: "600", color: C.text },
  fsContainer: { flex: 1, backgroundColor: "#000" },
  fsVideoArea: { flex: 1, backgroundColor: "#000" },
  fsSwipeOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
    zIndex: 5,
  },
  fsSwitchOverlay: {
    position: "absolute",
    alignSelf: "center",
    top: "50%",
    marginTop: -42,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.58)",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    zIndex: 8,
  },
  fsSwitchText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 8,
  },
  fsSwitchCount: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 11,
    marginTop: 3,
  },
  fsHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 10,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  fsHeaderBtn: { padding: 6 },
  fsHeaderLandscape: { paddingTop: 48 },
  fsHeaderPortrait: { paddingTop: 48 },
  fsTitle: {
    flex: 1,
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
    marginHorizontal: 4,
  },
  fsFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 8,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  fsFooterLandscape: { paddingBottom: 48 },
  fsFooterPortrait: { paddingBottom: 48 },
  fsPagerText: { color: "#fff", fontSize: 14, fontWeight: "700" },
  visibleVideo: { opacity: 1 },
  hiddenVideo: { opacity: 0 },
  thumbOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  spinner: {
    position: "absolute",
    alignSelf: "center",
    top: "50%",
    marginTop: -18,
  },
});
