import { StyleSheet } from "react-native";
import { BG, BRAND_RED, CARD_SHADOW } from "./listTheme";

export const sharedAssetListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG,
  },
  searchWrap: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
    backgroundColor: BG,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#EDF0F5",
    ...CARD_SHADOW,
  },
  searchIconWrap: {
    marginRight: 8,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  searchInput: {
    flex: 1,
    paddingVertical: 13,
    fontSize: 14,
    color: "#0F1923",
    fontWeight: "400",
  },
  spinnerWrap: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  clearButton: {
    padding: 4,
    marginLeft: 4,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 12,
  },
  summaryBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#FFF0F0",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#FFD6D6",
    flexShrink: 1,
  },
  summaryBadgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: BRAND_RED,
  },
  summaryMeta: {
    fontSize: 11.5,
    color: "#8A95A3",
    fontWeight: "500",
  },
  listContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  stickyHeader: {
    backgroundColor: BG,
    paddingHorizontal: 14,
    paddingTop: 2,
    paddingBottom: 10,
    zIndex: 10,
  },
  filterCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#EDF0F5",
    ...CARD_SHADOW,
  },
  filterCardIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF5F5",
    marginRight: 10,
  },
  filterCardContent: {
    flex: 1,
  },
  filterCardTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#0F1923",
    marginBottom: 2,
  },
  filterCardSub: {
    fontSize: 11.5,
    color: "#8A95A3",
  },
  emptyWrap: {
    alignItems: "center",
    paddingHorizontal: 32,
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 22,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    ...CARD_SHADOW,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#374151",
    marginBottom: 6,
    textAlign: "center",
  },
  emptySub: {
    fontSize: 12,
    color: "#8A95A3",
    textAlign: "center",
    lineHeight: 18,
  },
});
