import { StyleSheet } from "react-native";
import { BG, BRAND_RED, CARD_SHADOW } from "./listTheme";
import { C } from "../../../utils/helpers/colors";

export const sharedAssetListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG,
  },
  searchWrap: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
    backgroundColor: BG,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surface,
    minHeight: 48,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    ...CARD_SHADOW,
  },
  searchIconWrap: {
    marginRight: 8,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  searchInput: {
    flex: 1,
    height: 48,
    paddingVertical: 0,
    fontSize: 14,
    lineHeight: 20,
    color: C.text,
    fontWeight: "400",
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  spinnerWrap: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  clearButton: {
    padding: 4,
    marginLeft: 4,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 12,
  },
  summaryBadge: {
    alignSelf: "flex-start",
    backgroundColor: C.redSurface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: C.redBorder,
    minWidth: 0,
    flexShrink: 1,
  },
  summaryBadgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: BRAND_RED,
  },
  summaryMeta: {
    fontSize: 11.5,
    color: C.textSub,
    fontWeight: "500",
  },
  listContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  stickyHeader: {
    backgroundColor: BG,
    paddingHorizontal: 14,
    paddingTop: 2,
    paddingBottom: 10,
    zIndex: 10,
  },
  filterCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    ...CARD_SHADOW,
  },
  filterCardIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.redSurface,
    marginRight: 10,
  },
  filterCardContent: {
    flex: 1,
    minWidth: 0,
  },
  filterCardTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: C.text,
    marginBottom: 2,
  },
  filterCardSub: {
    fontSize: 11.5,
    color: C.textSub,
    flexShrink: 1,
  },
});
